config/routes.rb
Rails.application.routes.draw do
  resources :pictures
  resources :galleries do
    collection do
      get :mygalleries
    end  
  end  
  devise_for :users
  root 'galleries#index'

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  belongs_to :user
  has_many :pictures, dependent: :destroy
  accepts_nested_attributes_for :pictures, allow_destroy: true, reject_if: :all_blank
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :authenticate_user!,  only: [:mygalleries, :edit, :update, :destroy]
  before_action :set_gallery, only: [:show, :edit, :update, :destroy]

  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all
  end

  def mygalleries
    @galleries = Gallery.where(user:current_user)
    render :index
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
    @pictures = Picture.where(gallery_id:@gallery.id)
  end

  # GET /galleries/new
  def new
    @gallery = Gallery.new
    @gallery.pictures.build
  end

  # GET /galleries/1/edit
  def edit
    @gallery.pictures.build
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)
    if current_user
      @gallery.user = current_user
    end  
    respond_to do |format|
      if @gallery.save
        format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
        format.json { render :show, status: :created, location: @gallery }
      else
        format.html { render :new }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galleries/1
  # PATCH/PUT /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { render :show, status: :ok, location: @gallery }
      else
        format.html { render :edit }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to galleries_url, notice: 'Gallery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_params
      params.require(:gallery).permit(:name, :user_id, pictures_attributes: [:id, :picfile, :name, :_destroy])
    end
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/views/galleries/_form.html.slim
=form_for @gallery, class: 'form-inline' do |f|
  .panel.panel-default
    .panel-heading
      h4  Свойства
    .panel-body
      table.table
       tr
         td
           = f.label 'Название'
         td[colspan='2']
           .input-group
             = f.text_field :name, size: 24, maxlength: 20, placeholder: 'Как я провел лето...', class: 'form-control'
       tr
         td
           = f.label 'Мои фото'
         td
           .input-group
             = f.fields_for :pictures do |i|
               - if i.object.persisted?
                 .img-gal-item.pull-right
                   p = i.object.name
                   = image_tag i.object.picfile(:thumb), :class => 'img-rounded'
                   br
                   = link_to 'Удалить', picture_path(i.object), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Вы уверены?')) }, :class => 'btn btn-danger'
               - else
                 .pull-right
                   .duplicatable_nested_form
                     .row
                       .col-md-6
                         = i.text_field :name, placeholder: 'Название картинки'
                       .col-md-6
                         .file_browse_wrapper
                           = i.file_field :picfile
         td
           = link_to 'Добавить еще одну картинку', '#', class: 'duplicate_nested_form add-file btn btn-warning'
       tr
         td
           = f.submit 'Загрузить', class: 'btn btn-success'

app/views/galleries/_gallery.html.slim
tr
  td
    p = gallery.updated_at
    h3 = link_to gallery.name, gallery_path(gallery)
  td 
    p = gallery.user.email
  - if current_user and gallery.user == current_user
    td
      = link_to 'Редактировать', edit_gallery_path(gallery), class: 'btn btn-warning'
    td
      = link_to 'Удалить', gallery_path(gallery), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Вы уверены?')) }, :class => 'btn btn-danger'
  - else
    td[colspan='2']
      = link_to 'Смотреть', gallery_path(gallery), class: 'btn btn-success'

app/views/galleries/edit.html.slim
.page-header
  h1 Редактирование галереи
= render 'form'

app/views/galleries/index.html.slim
.panel.panel-default
  .panel-heading
    h1 Галереи
    - if current_user
      .path-selector
        = link_to 'Добавить галерею', new_gallery_path, class: 'btn btn-success'
  .panel-body
    table.table
      thead
        th Название
        th Автор
        - if current_user
          th[colspan='2'] Действия
      tbody
        = render @galleries
        

app/views/galleries/new.html.slim
.page-header
  h1 Новая галерея
= render 'form'

app/views/galleries/show.html.slim
.modal
  .modal-header
    = link_to 'x','#', class: 'close', "data-dismiss" => "modal"
    h3 Поделиться
  .modal-body
    h4 Поделиться
    p = gallery_path(@gallery)
  .modal-footer
    = link_to 'Закрыть','#', class: 'btn', "data-dismiss" => "modal"
.panel.panel-default
  .panel-heading
    h1 = @gallery.name
    - if current_user
      .path-selector
        .row
          .col-md-1.col-md-offset-8
            = link_to 'Поделиться','#', class: 'btn btn-success modal-toggle'
          .col-md-2
            = link_to 'Редактировать', edit_gallery_path(@gallery), class: 'btn btn-warning'
          .col-md-1
            = link_to 'Удалить', gallery_path(@gallery), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Вы уверены?')) }, :class => 'btn btn-danger'
  .panel-body
    table.table
      thead
        th Название
        th Картинка
        th[colspan='2'] Действия
      tbody
        = render @pictures